config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :bikes do
    resources :attendees, :controller => 'bike_attendees'
  end

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
  validates_presence_of :name
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  has_many :attendees
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bike_attendees_controller.rb
class BikeAttendeesController < ApplicationController
  def create
    @bike = Bike.find(params[:bike_id])
    @attendee = @bike.attendees.create(params[:attendee].permit(:name, :body))

    redirect_to bike_path(@bike)
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  before_action :set_bike, :only => [ :show, :edit, :update, :destroy]

  def index
    @bikes = Bike.all
    @bikes = Bike.page(params[:page]).per(5)
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    if @bike.save
      flash[:notice] = "was successfully created"
      redirect_to bikes_path
    else
      render :action => :new
    end
  end

  def show
    @page_title = @bike.name
  end

  def edit

  end

  def update
    if  @bike.update(bike_params)
      flash[:notice] = "was successfully updated"
      redirect_to bike_url(@bike)
    else
      render :action => :edit
    end
  end

  def destroy
    flash[:alert] = "was successfully deleted"
    @bike.destroy

    redirect_to bikes_url
  end

  private

  def set_bike
    @bike=Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:name, :description, :category_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bike_attendees_helper.rb
module BikeAttendeesHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bike_attendees/_attendee.html.erb
<% @bike.attendees.each do |attendee| %>
  <div class="panel panel-info"> <h5>Comment:</h5>
    <p><%=attendee.name %></p>
    <p><%=attendee.body %></p></div>
<%end %>

app/views/bike_attendees/_form.html.erb
<%= form_for ([@bike, @bike.attendees.build]) do |f| %>

  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :body, "Comment" %>
    <%= f.text_field :body %>
  </div>

  <%= f.submit %>

<%end %>

app/views/bikes/_form.html.erb
<p>
<%= f.label:name, "Name" %>
<%= f.text_field :name %>
</p>
<div class="form-group">
  <%= f.label:description, "Context" %>
  <%= f.text_area :description %>
</div>

app/views/bikes/edit.html.erb
<%= form_for @bike, url: bike_path, :method => :patch do |f| %>
  <%= render :partial => 'form', :locals =>{:f=>f} %>
  <%= f.submit "Update" %>
<% end %>

app/views/bikes/index.html.erb
<table class="table table-hover">
  <tr>
    <td><h3>Post</h3></td>
    <td><h3>Author</h3></td>
    <td><h3>Created time</h3></td>
    <td><h3>Function</h3></td>
  </tr>
  <% @bikes.try(:each) do |bike| %>
    <tr>
      <td>
        <%= bike.name %>
      </td>
      <td>
      </td>
      <td>
        <%= bike.created_at %>
      </td>
      <td>
        <%= link_to 'Show', bike_path(bike),:class=> "btn btn-default"%>
        <%= link_to 'Edit', edit_bike_path(bike),:class=> "btn btn-default" %>
        <%= link_to 'Delete', bike_path(bike), :method=> :delete, :class=> "btn btn-default" %>
      </td>
    </tr>
  <% end %>

</table>
<%= link_to 'New Bike', new_bike_path %></br>

<%= paginate @bikes %>

app/views/bikes/new.html.erb
<h2>New Post</h2>
<%= form_for @bike, url: bikes_path do |f|%>
  <p><%= render :partial =>'form', :locals =>{:f=>f} %></p>
  <p><%= f.submit "Create" %></p>
<% end %>

app/views/bikes/show.html.erb
<blockquote>
  <div>
    Classification: <%#= @bike.category.try(:name) %>
</div>
<h3>Title:</h3>
<div class="panel-heading"><%= @bike.name %></div>
<div class="panel-body">
  <p><%=simple_format @bike.description %></p>
</div>
</blockquote>

<p><%= link_to "Back to index", bikes_path %></p>

<h4><%= @bike.attendees.count %>Comments</h4>
<%#= render @event.comments %>

<div class="panel-footer">
  <%= render :partial=> 'bike_attendees/attendee' %>
</div>

</div>
<h4>Add a comment:</h4>
<%= render "bike_attendees/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mybike</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
      Hi, <%= current_user.email %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>
  <%= yield %>

  </body>
</html>